### ISSUE TITLE
Demo usage code fails

### ISSUE THREAD

**Issue by Alex-Muirhead** [KhushrajRathod/slack-bolt#4]
Running the demonstration [usage code](https://github.com/KhushrajRathod/slack-bolt#usage) with no modifications gives the following errors:
```output
error: TS2612 [ERROR]: Property 'resolve' will overwrite the base property in 'Deferred<undefined>'. If this is intentional, add an initializer. Otherwise, add a 'declare' modifier or remove the redundant declaration.
    public readonly resolve!: () => void;
                    ~~~~~~~
    at https://deno.land/x/evt@v1.9.12/tools/Deferred.ts:57:21

TS2322 [ERROR]: Type '{ token: string | undefined; text: string; channel: string; } | { token: string | undefined; channel: string; }' is not assignable to type 'ChatPostMessageArguments'.
  Property 'text' is missing in type '{ token: string | undefined; channel: string; }' but required in type 'ChatPostMessageArguments'.
                const postMessageArguments: ChatPostMessageArguments = typeof message === "string"
                      ~~~~~~~~~~~~~~~~~~~~
    at https://deno.land/x/slack_bolt@1.0.0/src/App.ts:762:23

    'text' is declared here.
        text: string
        ~~~~
        at https://deno.land/x/slack_web_api@1.0.1/src/methods.ts:948:5

Found 2 errors.
```

I'm using the following version of deno:
```
deno 1.11.4+ed16f43 (canary, x86_64-unknown-linux-gnu)
v8 9.1.269.35
typescript 4.3.2
```

**Comment by gatchan0807** [comment]
I also got the same error.
Version: Deno v1.16.4

So now I run it with `--no-check` only at runtime to go through the type check.
This has allowed me to use it without any problems.

In Deno v1.17.0 or later, I heard that you can use `--no-check=remote` to skip type checking of dependent libraries only.
So, I think it is possible to use this to check the type of the code you write, and deal with it on the user side.
https://github.com/denoland/deno/pull/12766
